/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TuBes;

import com.sun.imageio.stream.StreamCloser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ghost
 */
public class Membership extends javax.swing.JFrame {

    /**
     * Creates new form Membership
     */
    public Membership() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_Label2 = new javax.swing.JLabel();
        User_Label3 = new javax.swing.JLabel();
        Pass_Label4 = new javax.swing.JLabel();
        User_TextField2 = new javax.swing.JTextField();
        Yes_Button1 = new javax.swing.JButton();
        Password_Field1 = new javax.swing.JPasswordField();
        No_Button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplikasi Fitnes Center");

        Login_Label2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Login_Label2.setText("Login Membership Account");

        User_Label3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        User_Label3.setText("Username : ");

        Pass_Label4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Pass_Label4.setText("Password :");

        User_TextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_TextField2ActionPerformed(evt);
            }
        });

        Yes_Button1.setText("OK");
        Yes_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Yes_Button1ActionPerformed(evt);
            }
        });

        Password_Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_Field1ActionPerformed(evt);
            }
        });

        No_Button2.setText("Cancel");
        No_Button2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                No_Button2ItemStateChanged(evt);
            }
        });
        No_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(No_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(Yes_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Pass_Label4)
                                .addComponent(User_Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(User_TextField2)
                                .addComponent(Password_Field1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                    .addComponent(Login_Label2))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(User_TextField2)
                    .addComponent(User_Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pass_Label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Password_Field1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No_Button2)
                    .addComponent(Yes_Button1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_TextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_TextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_TextField2ActionPerformed

    private void Yes_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Yes_Button1ActionPerformed
        String user = User_TextField2.getText();
        String pass = Password_Field1.getText();
        if(user.equals("Admin") && pass.equals("123")){
            JOptionPane.showMessageDialog(null, "Login Akun Berhasil! ");
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Username atau Password salah! ");
        }
    }//GEN-LAST:event_Yes_Button1ActionPerformed

    private void Password_Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_Field1ActionPerformed
        
    }//GEN-LAST:event_Password_Field1ActionPerformed

    private void No_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_Button2ActionPerformed
        dispose();
        Fitness ft = new Fitness();
        ft.Membership_ComboBox1.setVisible(false);
        ft.Membership_ComboBox1.setEnabled(false);
        
 
    }//GEN-LAST:event_No_Button2ActionPerformed

    private void No_Button2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_No_Button2ItemStateChanged
        // TODO add your handling code here:
//        new Fitness().Membership_ComboBox1.setVisible(false);
    }//GEN-LAST:event_No_Button2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Membership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_Label2;
    public static javax.swing.JButton No_Button2;
    private javax.swing.JLabel Pass_Label4;
    private javax.swing.JPasswordField Password_Field1;
    private javax.swing.JLabel User_Label3;
    private javax.swing.JTextField User_TextField2;
    private javax.swing.JButton Yes_Button1;
    // End of variables declaration//GEN-END:variables
}
